name: Run reusable geant-val CI workflow

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write  # This allows GitHub Actions to push changes
  
jobs:
  call-reusable:
    uses: geant-val/geant-val-ci-workflows/.github/workflows/geant-val-ci-workflows.yaml@main
    with:
      commit_back: true
